/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

let isEmailExist = false;


$(document).ready(function () {
    $("#loginForm").show();
    $("#registerForm").hide();
});

$("#authType input").change(function () {
    if ($(this).val() == "login") {
        $("#loginForm").fadeIn();
        $("#registerForm").hide();
        $("#bookButton").val("Login Now");
        document.getElementById("formHeading").textContent = "Login to continue!";
    } else if ($(this).val() == "register") {
        $("#loginForm").hide();
        $("#registerForm").fadeIn();
        $("#bookButton").val("Register Now");
        document.getElementById("formHeading").textContent = "Register with us!";

    }
});

/*
 **********************************************************
 *  Checks whether email exist in database,
 *  when user clicks out of input box after entering email
 **********************************************************
 */
document.getElementById("email").addEventListener("blur", function (e) {
    let valid = true;
    $('[required]').each(function () {
        if ($(this).is(':invalid') || !$(this).val())
            valid = false;
    });
    if (valid) {
        $.ajax({
            type: 'get',
            url: './php/validate.php',
            data: {'email': $('#email').val()},
            cache: false,
            success: function (response) {
                console.log(response);
                if (response === "nExist") {
                    $('#invalidEmail').attr("hidden", "hidden");
                    $('#verifyEmailButton').removeAttr("hidden");
                    isEmailExist = false;

                } else {
                    $('#invalidEmail').removeAttr("hidden");
                    $('#verifyEmailButton').attr("hidden", "hidden");
                    isEmailExist = true;

                }
            },
            error: function (error) {
                console.log(error);
            }
        });
    } else {
        console.log($("#email").text().trim());
        console.log(valid);
    }

});

/*
 *******************************************
 * Send a verification otp if email is valid
 *******************************************
 */
$('#verifyEmailButton').on("click", function () {
    if ($(this).text() === "Verify Email!") {
        $(this).text("wait...");
        $.ajax({
            type: 'post',
            url: './php/sendOTP.php',
            data: {'email': $('#email').val()},
            cache: false,
            success: function (response) //Response contains otp generated by sendOTP.php
            {
                if (response == 200) {
                    checkOTP();
                } else {
                    alert("Something went wrong");
                }

            }
        });
        /*
         * ******************************************************************************
         * If user cancelled prompt without submitting OTP and clicks on Enter OTP later.
         * ******************************************************************************
         */
    } else if ($(this).text() === "Enter OTP") {
        checkOtp();
    }
});

/*
 ******************************************************
 * Checks user entered otp with generated otp for email
 ******************************************************
 */
function checkOTP() {
    let OTP = prompt("Enter OTP sent to " + $("#email").val());
    if (OTP.trim() != "") {
        $.ajax({
            method: "post",
            url: "./php/checkOTP.php",
            data: {"otp": OTP},
            success: function (response) {
                //
                console.log(response);
                if(response == 200){
                    
                }else if(response == 0){
                    alert("Wrong OTP");
                } else if(response == -1){
                    alert("Something went wrong");
                }
            }
        });
    } else {
        $("#verifyEmailButton").text("Enter OTP");
    }
}
//    return new Promise((resolve, reject) => {
//        if (response !== -1) {
//            const OTP = prompt("Enter OTP sent to " + $('#email').val());
//            if (OTP === response) {
//                $("#verifyEmailButton").replaceWith("Email verified!");
//
//                resolve(SUCCESS_CODE);
//            } else if (OTP !== response && OTP !== null) {
//                alert("Invalid Email OTP. Try Again");
//
//            } else {
//                reject(response); //If user click on cancel.
//            }
//        }
//    });




