/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$(document).ready(function () {
    $("#loginForm").show();
    $("#registerForm").hide();
});

$("#authType input").change(function () {
    if ($(this).val() == "login") {
        $("#loginForm").fadeIn();
        $("#registerForm").hide();
        $("#bookButton").val("Login Now");
        document.getElementById("formHeading").textContent = "Login to continue!";
    } else if ($(this).val() == "register") {
        $("#loginForm").hide();
        $("#registerForm").fadeIn();
        $("#bookButton").val("Register Now");
        document.getElementById("formHeading").textContent = "Register with us!";

    }
});

/*
 **********************************************************
 *  Checks whether email exist in database,
 *  when user clicks out of input box after entering email
 **********************************************************
 */
document.getElementById("emailReg").addEventListener("blur", function (e) {
    let valid = true;
    $('[required]').each(function () {
        if ($(this).attr("id") == "emailReg") {
            if ($(this).is(':invalid') || !$(this).val())
                valid = false;
        }
    });
    if (valid && $("#emailReg").val().trim() != "") {
        $.ajax({
            type: 'get',
            url: './php/validate.php',
            data: {'email': $('#emailReg').val().trim()},
            cache: false,
            success: function (response) {
                if (response === "nExist") {
                    $('#invalidEmail').attr("hidden", "hidden");
                    $('#verifyEmailButton').removeAttr("hidden");

                } else {
                    $('#invalidEmail').removeAttr("hidden");
                    $('#verifyEmailButton').attr("hidden", "hidden");

                }
            },
            error: function (error) {
                console.log(error);
            }
        });
    }

});

/*
 *******************************************
 * Send a verification otp if email is valid
 *******************************************
 */
$('#verifyEmailButton').on("click", function () {
    if ($(this).text() === "Verify Email!") {
        $(this).text("wait...");
        $.ajax({
            type: 'post',
            url: './php/sendOTP.php',
            data: {'email': $('#emailReg').val()},
            cache: false,
            success: function (response) //Response contains otp generated by sendOTP.php
            {
                if (response == 200) {
                    checkOTP();
                } else {
                    alert("Something went wrong");
                }

            }
        });
        /*
         * ******************************************************************************
         * If user cancelled prompt without submitting OTP and clicks on Enter OTP later.
         * ******************************************************************************
         */
    } else if ($(this).text() === "Enter OTP") {
        checkOTP();
    }
});

/*
 ******************************************************
 * Checks user entered otp with generated otp for email
 ******************************************************
 */
function checkOTP() {
    let OTP = prompt("Enter OTP sent to " + $("#emailReg").val());
    if (OTP != null) {
        if (OTP.trim() != "") {
            $.ajax({
                method: "post",
                url: "./php/checkOTP.php",
                data: {"otp": OTP},
                success: function (response) {
                    if (response == 200) {
                        $("#verifyEmailButton").text("Email verified!");
                        $("#emailReg").attr("disabled", "disabled");
                        isEmailVerified = true;
                    } else if (response == 0) {
                        isEmailVerified = false;
                        alert("Wrong OTP");
                        $("#verifyEmailButton").text("Enter OTP");
                    } else if (response == -1) {
                        isEmailVerified = false;
                        alert("Something went wrong");
                    }
                }
            });
        }
    } else {
        $("#verifyEmailButton").text("Enter OTP");
    }

}

/*
 *****************************************************************
 *  Checks whether phone number exist in database,
 *  when user clicks out of input box after entering phone number
 *****************************************************************
 */
document.getElementById("phoneReg").addEventListener("blur", function (e) {
    let valid = true;
    $('[required]').each(function (e) {
        if ($(this).attr("id") == "phone") {
            if ($(this).is(':invalid') || !$(this).val())
                valid = false;
        }
    });
    if (valid && $("#phoneReg").val().trim() != "") {
        $.ajax({
            type: 'get',
            url: './php/validate.php',
            data: {'phone': $('#phoneReg').val().trim()},
            cache: false,
            success: function (response) {
                if (response === "nExist") {
                    $('#invalidPhone').attr("hidden", "hidden");
                    $('#verifyPhoneButton').removeAttr("hidden");

                } else {
                    $('#invalidPhone').removeAttr("hidden");
                    $('#verifyPhoneButton').attr("hidden", "hidden");

                }
            },
            error: function (error) {
                console.log(error);
            }
        });
    }

});

/*
 *******************************************
 * Send a verification otp if email is valid
 *******************************************
 */
$('#verifyPhoneButton').on("click", function () {
    if ($(this).text() === "Verify Phone!") {
        $(this).text("wait...");
        $.ajax({
            type: 'post',
            url: './php/sendOTP.php',
            data: {'phone': $('#phoneReg').val()},
            cache: false,
            success: function (response) //Response contains otp generated by sendOTP.php
            {
                if (response == 200) {
                    checkPhoneOTP();
                } else {
                    alert("Something went wrong");
                }

            }
        });
        /*
         * ******************************************************************************
         * If user cancelled prompt without submitting OTP and clicks on Enter OTP later.
         * ******************************************************************************
         */
    } else if ($(this).text() === "Enter OTP") {
        checkPhoneOTP();
    }
});

/*
 ******************************************************
 * Checks user entered otp with generated otp for phone
 ******************************************************
 */

function checkPhoneOTP() {
    let OTP = prompt("Enter OTP sent to " + $("#phoneReg").val());
    if (OTP != null) {
        if (OTP.trim() != "") {
            $.ajax({
                method: "post",
                url: "./php/checkOTP.php",
                data: {"otp": OTP},
                success: function (response) {
                    if (response == 200) {
                        $("#verifyPhoneButton").text("Phone verified!");
                        $("#phoneReg").attr("disabled", "disabled");
                    } else if (response == 0) {
                        alert("Wrong OTP");
                        $("#verifyPhoneButton").text("Enter OTP");
                    } else if (response == -1) {
                        alert("Something went wrong");
                    }
                }
            });
        }
    } else {
        $("#verifyPhoneButton").text("Enter OTP");
    }
}

/*
 *********************************************************
 *  Checks password length on value change of input field
 *********************************************************
 */

$('#password').keyup(function () {
    if ($(this).val().length < 6) {
        $('#invalidLength').removeAttr("hidden");
    } else {
        $('#invalidLength').attr("hidden", "hidden");
    }
});

/*
 ********************************************
 *  Checks confirm password matches password
 ********************************************
 */
$('#conPassword').keyup(function () {
    if ($(this).val() !== $('#password').val()) {
        $('#invalidConPassword').removeAttr("hidden");
        $('#validConPassword').attr("hidden", "hidden");
        isPasswordMatched = false;


    } else {
        $('#invalidConPassword').attr("hidden", "hidden");
        $('#validConPassword').removeAttr("hidden");
        isPasswordMatched = true;
    }
});

//On form submit
$('#loginForm').on("submit", function (e) {
    e.preventDefault();
    loginUser();
});

function loginUser() {
    $.ajax({
        type: 'POST',
        url: './php/loginUser.php',
        data: $("#loginForm").serialize(),
        cache: false,
        success: function (response) {
            if (response == 1) {
                window.location.href = "./php/admin/index.php";
            } else if (response == 0) {
                window.location.href = "./php/user/index.php";
            } else if (response == -1) {
                alert("Your account is blocked, contact admin");
            } else if (response == -2) {
                alert("Incorrect credentials!\nAre you trying to register?");
            }else{
                alert("Something went wrong!");
            }
        }
    });
}

$('#registerForm').on("submit", function (e) {
    e.preventDefault();

    let formData = new FormData();
    formData.append('name', $("#nameInputReg input").val());
    formData.append('email', $("#emailInputReg input").val());
    formData.append('phone', $("#phoneInputReg input").val());
    formData.append('password', $("#passwordInputReg input").val());
    formData.append('file', $('input[type=file]')[0].files[0]);

    registerUser(formData);
});


function registerUser(formData) {
   
    if (($("#password").val().length >= 6) && ($("#conPassword").val() == $('#password').val())) {

        $.ajax({
            type: 'POST',
            url: './php/registerUser.php',
            enctype: 'multipart/form-data',
            data: formData,
            contentType: false,
            cache: false,
            processData: false,
            success: function (response) {
                if (response == -2) {
                    alert("Please Verify phone first!");
                } else if (response == -1) {
                    alert("Please verify email first!");
                } else if (response == 200) {
                    let res = confirm("Successfully registered!\nLogin to continue!");
                    if (res) {
                        location.reload();
                    }
                } else {
                    alert("Something went wrong!\nTechnical Details: " + response);
                }
            },
            complete: function () {
            }
        });
    }
}